### ISSUE TITLE
Circular import of analysis_window

### ISSUE THREAD

**Issue by tombsar** [torebutlin/cued_datalogger#10]
Trying to run the datalogger gives me the following error:

```
~$ cued_datalogger
Traceback (most recent call last):
  File "/usr/local/bin/cued_datalogger", line 7, in <module>
    from cued_datalogger.__main__ import run
  File "/usr/local/lib/python3.4/dist-packages/cued_datalogger/__init__.py", line 4, in <module>
    from cued_datalogger.analysis import analysis_window as analysis_window
  File "/usr/local/lib/python3.4/dist-packages/cued_datalogger/analysis/analysis_window.py", line 11, in <module>
    from cued_datalogger.analysis.circle_fit import CircleFitWidget, CircleFitToolbox
  File "/usr/local/lib/python3.4/dist-packages/cued_datalogger/analysis/circle_fit.py", line 6, in <module>
    from cued_datalogger.api.workspace import Workspace
  File "/usr/local/lib/python3.4/dist-packages/cued_datalogger/api/workspace.py", line 6, in <module>
    from cued_datalogger.analysis import analysis_window
ImportError: cannot import name 'analysis_window'
```

It looks as though `analysis.analysis_window` imports `analysis.circle_fit`, which imports `api.workspace`, which tries to import `analysis.analysis_window` again.

Edit: OS is Debian oldstable (8.9) with Python 3.4. datalogger installed from pip

**Comment by ghost** [comment]
How is your version installed? Did you clone the repo and try and an run it directly or did you install the package via pip?

**Comment by tombsar** [comment]
Installed via pip. Is the github repository more up to date?

**Comment by tombsar** [comment]
Interestingly this problem does not seem to occur on my other Debian (buster/sid) PC with Python 3.5. I'm guessing it's an installation issue.
