### ISSUE TITLE
to_dB causes ValueError in pyqtgraph

### ISSUE THREAD

**Issue by ghost** [torebutlin/cued_datalogger#4]
(Probably something to do with nans and infs)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyqtgraph/graphicsItems/PlotCurveItem.py", line 175, in boundingRect
    (ymn, ymx) = self.dataBounds(ax=1)
  File "/usr/local/lib/python3.5/dist-packages/pyqtgraph/graphicsItems/PlotCurveItem.py", line 135, in dataBounds
    b = (d.min(), d.max())
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity

```

**Comment by ghost** [comment]
Fixed in bd534dca012ccbde364d67abfa44fbc821762485
Use numpy's ``isfinite`` function to mask out all of the nans and infs, then convert them to zeros.
