### ISSUE TITLE
Exception in switching to circlefit tab with built in data

### ISSUE THREAD

**Issue by ghost** [torebutlin/cued_datalogger#5]
Clicking 'Convert to Circle Fit' raises the following error:
```
Traceback (most recent call last):

  File "/home/theo/Documents/cambridge/urop/cued_datalogger/cued_datalogger/analysis/analysis_window.py", line 327, in circle_fitting
    self.display_tabwidget.circle_widget.set_selected_channels(self.cs.channels)

  File "/home/theo/Documents/cambridge/urop/cued_datalogger/cued_datalogger/analysis/circle_fit.py", line 331, in set_selected_channels
    pen=channel.colour)

  File "/usr/local/lib/python3.5/dist-packages/pyqtgraph/graphicsItems/PlotDataItem.py", line 177, in __init__
    self.setData(*args, **kargs)

  File "/usr/local/lib/python3.5/dist-packages/pyqtgraph/graphicsItems/PlotDataItem.py", line 461, in setData
    self.updateItems()

  File "/usr/local/lib/python3.5/dist-packages/pyqtgraph/graphicsItems/PlotDataItem.py", line 487, in updateItems
    self.curve.setData(x=x, y=y, **curveArgs)

  File "/usr/local/lib/python3.5/dist-packages/pyqtgraph/graphicsItems/PlotCurveItem.py", line 307, in setData
    self.updateData(*args, **kargs)

  File "/usr/local/lib/python3.5/dist-packages/pyqtgraph/graphicsItems/PlotCurveItem.py", line 353, in updateData
    raise Exception("X and Y arrays must be the same shape--got %s and %s." % (self.xData.shape, self.yData.shape))

Exception: X and Y arrays must be the same shape--got (1251,) and (0,).
```

**Comment by ghost** [comment]
When transfer functions are calculated, not all channels have a transfer function. Circle fit was not checking whether the dataset  "TF" existed, and so everything fell over when it tried to plot.

Fixed in 99a21610191080d6e4ddfc6411f5f0420bc67934
